-- +goose Up

-- Composite indexes for common multi-column filter patterns.
-- Single-column indexes on org_id already exist (migration 000010, 000016).
-- These partial composite indexes cover the WHERE clauses generated by List()
-- and keep planner costs low for the most frequent filter combinations.

-- Tickets
CREATE INDEX idx_tickets_org_status     ON tickets (org_id, status)      WHERE deleted_at IS NULL;
CREATE INDEX idx_tickets_org_priority   ON tickets (org_id, priority)    WHERE deleted_at IS NULL;
CREATE INDEX idx_tickets_org_assignee   ON tickets (org_id, assignee_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_tickets_org_created    ON tickets (org_id, created_at DESC) WHERE deleted_at IS NULL;

-- Deals
CREATE INDEX idx_deals_org_stage        ON deals (org_id, stage)         WHERE deleted_at IS NULL;
CREATE INDEX idx_deals_org_owner        ON deals (org_id, owner_id)      WHERE deleted_at IS NULL;
CREATE INDEX idx_deals_org_created      ON deals (org_id, created_at DESC) WHERE deleted_at IS NULL;

-- Accounts
CREATE INDEX idx_accounts_org_owner     ON accounts (org_id, owner_id)   WHERE deleted_at IS NULL;
CREATE INDEX idx_accounts_org_created   ON accounts (org_id, created_at DESC) WHERE deleted_at IS NULL;

-- Contacts
CREATE INDEX idx_contacts_org_owner     ON contacts (org_id, owner_id)   WHERE deleted_at IS NULL;
CREATE INDEX idx_contacts_org_created   ON contacts (org_id, created_at DESC) WHERE deleted_at IS NULL;

-- +goose Down

DROP INDEX IF EXISTS idx_contacts_org_created;
DROP INDEX IF EXISTS idx_contacts_org_owner;
DROP INDEX IF EXISTS idx_accounts_org_created;
DROP INDEX IF EXISTS idx_accounts_org_owner;
DROP INDEX IF EXISTS idx_deals_org_created;
DROP INDEX IF EXISTS idx_deals_org_owner;
DROP INDEX IF EXISTS idx_deals_org_stage;
DROP INDEX IF EXISTS idx_tickets_org_created;
DROP INDEX IF EXISTS idx_tickets_org_assignee;
DROP INDEX IF EXISTS idx_tickets_org_priority;
DROP INDEX IF EXISTS idx_tickets_org_status;
