-- +goose Up
-- +goose StatementBegin
ALTER TABLE org_settings
    ADD COLUMN IF NOT EXISTS company_name TEXT,
    ADD COLUMN IF NOT EXISTS company_logo_url TEXT,
    ADD COLUMN IF NOT EXISTS company_website TEXT,
    ADD COLUMN IF NOT EXISTS company_email TEXT,
    ADD COLUMN IF NOT EXISTS company_phone TEXT,
    ADD COLUMN IF NOT EXISTS company_address_line1 TEXT,
    ADD COLUMN IF NOT EXISTS company_address_line2 TEXT,
    ADD COLUMN IF NOT EXISTS company_city TEXT,
    ADD COLUMN IF NOT EXISTS company_state TEXT,
    ADD COLUMN IF NOT EXISTS company_postal_code TEXT,
    ADD COLUMN IF NOT EXISTS company_country TEXT,
    ADD COLUMN IF NOT EXISTS portal_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS portal_display_name TEXT,
    ADD COLUMN IF NOT EXISTS portal_announcement TEXT,
    ADD COLUMN IF NOT EXISTS portal_default_assignee_id UUID,
    ADD COLUMN IF NOT EXISTS portal_menu JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS portal_shortcuts JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS portal_recent_widget_limit INTEGER NOT NULL DEFAULT 5,
    ADD COLUMN IF NOT EXISTS smtp_host TEXT,
    ADD COLUMN IF NOT EXISTS smtp_port INTEGER,
    ADD COLUMN IF NOT EXISTS smtp_username TEXT,
    ADD COLUMN IF NOT EXISTS smtp_from_email TEXT,
    ADD COLUMN IF NOT EXISTS smtp_from_name TEXT,
    ADD COLUMN IF NOT EXISTS smtp_security TEXT,
    ADD COLUMN IF NOT EXISTS smtp_auth_type TEXT,
    ADD COLUMN IF NOT EXISTS smtp_password_enc TEXT,
    ADD COLUMN IF NOT EXISTS config_support_email TEXT,
    ADD COLUMN IF NOT EXISTS config_upload_max_mb INTEGER NOT NULL DEFAULT 25,
    ADD COLUMN IF NOT EXISTS config_default_page_size INTEGER NOT NULL DEFAULT 25,
    ADD COLUMN IF NOT EXISTS config_list_preview_chars INTEGER NOT NULL DEFAULT 120,
    ADD COLUMN IF NOT EXISTS menu_config JSONB NOT NULL DEFAULT '{}'::jsonb;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE org_settings
    DROP COLUMN IF EXISTS menu_config,
    DROP COLUMN IF EXISTS config_list_preview_chars,
    DROP COLUMN IF EXISTS config_default_page_size,
    DROP COLUMN IF EXISTS config_upload_max_mb,
    DROP COLUMN IF EXISTS config_support_email,
    DROP COLUMN IF EXISTS smtp_password_enc,
    DROP COLUMN IF EXISTS smtp_auth_type,
    DROP COLUMN IF EXISTS smtp_security,
    DROP COLUMN IF EXISTS smtp_from_name,
    DROP COLUMN IF EXISTS smtp_from_email,
    DROP COLUMN IF EXISTS smtp_username,
    DROP COLUMN IF EXISTS smtp_port,
    DROP COLUMN IF EXISTS smtp_host,
    DROP COLUMN IF EXISTS portal_recent_widget_limit,
    DROP COLUMN IF EXISTS portal_shortcuts,
    DROP COLUMN IF EXISTS portal_menu,
    DROP COLUMN IF EXISTS portal_default_assignee_id,
    DROP COLUMN IF EXISTS portal_announcement,
    DROP COLUMN IF EXISTS portal_display_name,
    DROP COLUMN IF EXISTS portal_enabled,
    DROP COLUMN IF EXISTS company_country,
    DROP COLUMN IF EXISTS company_postal_code,
    DROP COLUMN IF EXISTS company_state,
    DROP COLUMN IF EXISTS company_city,
    DROP COLUMN IF EXISTS company_address_line2,
    DROP COLUMN IF EXISTS company_address_line1,
    DROP COLUMN IF EXISTS company_phone,
    DROP COLUMN IF EXISTS company_email,
    DROP COLUMN IF EXISTS company_website,
    DROP COLUMN IF EXISTS company_logo_url,
    DROP COLUMN IF EXISTS company_name;
-- +goose StatementEnd
